name: Terraform

on:
  push:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.4"
      
      - name: Terraform fmt
        working-directory: modules/services/yandex-cloud
        id: fmt
        run: |
          terraform fmt
        continue-on-error: true

      - name: Terrafrom init
        working-directory: modules/services/yandex-cloud
        id: init
        run: |
          terraform init

      - name: Terraform validate
        working-directory: modules/services/yandex-cloud
        id: validate
        run: |
          terraform validate
      
      - name: Terraform plan
        working-directory: modules/services/yandex-cloud
        run: terraform plan
        continue-on-error: true