name: Terraform

on:
  push:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.4"
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terrafrom init
        id: init
        run: terraform init

      - name: Terraform validate
        id: validate
        run: terraform validate
      
      - name: Terraform plan
        run: terraform plan
        continue-on-error: true

      - name: 